### ISSUE TITLE
Koupíme si mælk

### ISSUE THREAD

**Issue by effa** [effa/erasmus#2]

**Comment by jirmauritz** [comment]
![Mྀælk](https://lh3.googleusercontent.com/y0NcxvesJy6bYZEBVArRr-8EWiZImjfaGDj1i2QhlTDVqtbvOXA_igPhD08rV8Z3Sz36iW4YJgoBF8mJ6HxH6uamz-qFnFIxJ03V97KuRi0lR0r-jS4SKwZ_HhZfdOVcI7UChdmh_uzt7rq8fvWLkx05jzy2QLhXZMZPDD3JEUep-5HCOY7WIOyQxVvC8ybNmgjk8y9TIYcGIjaOo2jpeHJb-aLUB6bxItzT2cEy-nGcPUTJgnUukg1cGKpDwBO6sJSgx6z2Wa8VxUTU-xPjTosDNHQrDZanOfJe5jKc5DjmQXUpXTxrjAGcj03jplfUYpc1QKWHjW-YTUp88eJb4nBwELHabYCI3_VjrLKsrqSP8DaGuT4X9R6br4O9BCV0J5LUWQqWIA4N8ezkWGOOoA8NKtnLMM6cRm8zsi9k3D1hsrMoeB_E7gvDYgG2dzW1OlcFjS-uqmTxg0eTY_3XlSZ_HMWprMnGTE3CTb8fUt9zT2gVqdNvaYkZ9Pp6DRAapJXa4SjHtDDS5YdkPaunSVq3MrW0hl8P13SVdO8jpl1Nv0wzUAd67-V-W-yqtrl86-wR=w1119-h632-no)
Done.
