### ISSUE TITLE
Popíšeme tabuli důkazem 3. Riceovy věty + dánsky "Nemazat".

### ISSUE THREAD

**Issue by effa** [effa/erasmus#24]

**Comment by effa** [comment]
Zvládnuto!

**Comment by Bender250** [comment]
Nebyla by fotka + hlaseni, jak dlouho to tam setrvava?

**Comment by effa** [comment]
Fotku máme, dáme ji do článku na blog. Napsali jsme to teprve včera, taky mě zajímá, jak dlouho to tam vydrží.
