### ISSUE TITLE
Každodenní cíle

### ISSUE THREAD

**Issue by effa** [effa/erasmus#27]
1. Alespoň 60 minut pohybu (denně).
2. Každý den alespoň 5 kusů ovoce a zeleniny.
3. Maximálně 3 piva denně.
4. Alespoň hodinu denně pracovat na projektu do laboratoře.
5. Naučíme se 5 nových dánských slov.
6. Minimálně 2krát týdně rybu.
7. Alespoň 1 sport/posilku (jízda na kole se nepočítá) týdně.
8. Alespoň 1 cyklistický výlet týdně.
9. Přečíst 1 odborný článek nebo knížku týdně.

|  | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
| --: | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1.1. | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ |
| 2.1. | ✔ | ✗ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ |
| 3.1. | ✔ | ✔ | ✔ | ✗ | ✔ | ✔ | ✔ | ✔ | ✔ |
| 4.1. | ✔ | ✗ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ |
| 5.1. | ✔ | ✔ | ✗ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ |
| 6.1. | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ |
| 7.1. | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ |
| 8.1. | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✗ |
| 9.1. | ✔ | ✗ | ✗ | ✔ | ✗ | ✔ | ✔ | ✔ | ✗ |
| 10.1. | ✔ | ✗ | ✔ | ✗ | ✗ | ✔ | ✔ | ✔ | ✗ |
| 11.1. | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✗ |
| 12.1. | ✔ | ✗ | ✔ | ✔ | ✗ | ✔ | ✔ | ✔ | ✗ |
| 13.1. | ✗ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✗ |
| 14.1. | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✗ |

Done: ✔ (musí splnit Jirka i Tom)
Fail:  ✗

**Comment by Bender250** [comment]
Co pridat "jednou tydne napsat blog"? Mne se to dari alespon v 50 % tydnu :D.

**Comment by effa** [comment]
Dobrý nápad, zvážíme přidání při vytváření dalšího milestonu.
