### ISSUE TITLE
Pridať na blog RSS feed

### ISSUE THREAD

**Issue by mukrop** [effa/erasmus#30]

**Comment by effa** [comment]
Zkusil jsem to, ale nejsem schopen na jisto ověřit, jestli to funguje, nebo jestli tam není nějaký problém. V neděli nejspíš budeme přidávat další článek, tak uvidím (a případně uzavřu issue, pokud by bylo všechno v pohodě). Pokud s tím narazíš na nějaký problém, tak napiš.

**Comment by mukrop** [comment]
Vyzera to funkcne, dik. Ak by bol nejaky problem, ozvem sa.
