### ISSUE TITLE
Vysvetliť, čo znamená milestone Mælk?

### ISSUE THREAD

**Issue by xlauko** [effa/erasmus#31]

**Comment by effa** [comment]
Každých 14 dní máme meeting, na kterém si vytvoříme seznam úkolů, které chceme zvládnout v dalších dvou týdnech. Tyto dvoutýdenní sprinty (milestony) pojmenováváme podle názvů potravin v dánštině, které budeme zrovna kupovat (viz issue #2). Jako první jsme zvolili _Mælk_, tedy _mléko_.
