### ISSUE TITLE
Sepsat a rozeslat email motivující k organizaci InterSøBa

### ISSUE THREAD

**Issue by jirmauritz** [effa/erasmus#36]

**Comment by Bender250** [comment]
Chci vic informaci o teto myslence :D.

**Comment by effa** [comment]
No zatím k tomu bohužel není nic víc co říct. Ale snad brzo bude. Zatím máme návrh na název: _InterSøB -- Interdisciplinær Søndag Begejstring_ (~ interdisciplinární nedělní nadšení). Nápady na vhodnější dánské slovo začínající na B vítány.

**Comment by effa** [comment]
Sepsáno a rozesláno.
